### ISSUE TITLE
Task :app:dexBuilderDebug failed cause of YandexMetrica

### ISSUE THREAD

**Issue by faizksen** [stefan-zobel/streamsupport#18]
I am using MQTT in my project and I can't build the app cause of

```
Task :app:dexBuilderDebug
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.r8: Class content provided for type descriptor com.yandex.metrica.impl.ob.j actually defines class com.yandex.metrica.impl.ob.J","sources":[{"file":"D:\\ThisProgect\\app\\build\\intermediates\\transforms\\androidRetroFix\\debug\\67.jar"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.r8: Class content provided for type descriptor com.yandex.metrica.impl.ob.lf actually defines class com.yandex.metrica.impl.ob.Lf","sources":[{"file":"D:\\ThisProgect\\app\\build\\intermediates\\transforms\\androidRetroFix\\debug\\67.jar"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.r8: Class content provided for type descriptor com.yandex.metrica.impl.ob.fk actually defines class com.yandex.metrica.impl.ob.Fk","sources":[{"file":"D:\\ThisProgect\\app\\build\\intermediates\\transforms\\androidRetroFix\\debug\\67.jar"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.r8: Class content provided for type descriptor com.yandex.metrica.impl.ob.d3 actually defines class com.yandex.metrica.impl.ob.D3","sources":[{"file":"D:\\ThisProgect\\app\\build\\intermediates\\transforms\\androidRetroFix\\debug\\67.jar"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.r8: Class content provided for type descriptor com.yandex.metrica.impl.ob.Xf actually defines class com.yandex.metrica.impl.ob.xf","sources":[{"file":"D:\\ThisProgect\\app\\build\\intermediates\\transforms\\androidRetroFix\\debug\\67.jar"}],"tool":"D8"}
```

full
[yandexIssue.txt](https://github.com/stefan-zobel/streamsupport/files/8243376/yandexIssue.txt)

Gradle files are configured as described in [docs](https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/)

my build.gradle, i'm using `gradle-7.0.2` (tried with java 1.8 and 11):
```
buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'gradle.plugin.com.github.sgtsilvio.gradle:android-retrofix:0.4.1'
    }
}

apply plugin: 'com.github.sgtsilvio.gradle.android-retrofix'

android {
    compileSdkVersion 31
    buildToolsVersion '31.0.0'

    configurations {
        all {
            exclude module: 'commons-logging'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
//        sourceCompatibility JavaVersion.VERSION_1_8
//        targetCompatibility JavaVersion.VERSION_1_8
    }

   defaultConfig {
        applicationId "com.thisproject.project"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 296
        versionName '6.2.2'
        multiDexEnabled true
        ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
    }

   debug {
            applicationIdSuffix ".debug"
            debuggable true
            minifyEnabled false
            zipAlignEnabled false
            shrinkResources false
            multiDexKeepFile file('multidex-config.txt')
   }

dependencies {
   ...
   implementation 'com.hivemq:hivemq-mqtt-client:1.3.0'
   implementation 'net.sourceforge.streamsupport:android-retrostreams:1.7.4'
   implementation 'net.sourceforge.streamsupport:android-retrofuture:1.7.4'
   implementation 'com.yandex.android:mobmetricalib:4.2.0'
   ...
}
```
 
Hope you can help me.

**Comment by faizksen** [comment]
And when I remove Yandex from the project, I get the following error at runtime (if i change build variand to debug, it's the same):

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thisproject.project.release, PID: 27649
    java.lang.RuntimeException: Unable to instantiate application com.thisproject.project.MainApplication package com.thisproject.project.release: java.lang.ClassNotFoundException: Didn't find class "com.thisproject.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~e3avWk9zFUDb8PcMaDzW2A==/com.thisproject.project.release-M7L_fDLXDMIr_wY7b6al4Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~e3avWk9zFUDb8PcMaDzW2A==/com.thisproject.project.release-M7L_fDLXDMIr_wY7b6al4Q==/lib/arm64, /data/app/~~e3avWk9zFUDb8PcMaDzW2A==/com.thisproject.project.release-M7L_fDLXDMIr_wY7b6al4Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6689)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.thisproject.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~e3avWk9zFUDb8PcMaDzW2A==/com.thisproject.project.release-M7L_fDLXDMIr_wY7b6al4Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~e3avWk9zFUDb8PcMaDzW2A==/com.thisproject.project.release-M7L_fDLXDMIr_wY7b6al4Q==/lib/arm64, /data/app/~~e3avWk9zFUDb8PcMaDzW2A==/com.thisproject.project.release-M7L_fDLXDMIr_wY7b6al4Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6689) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:247) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by stefan-zobel** [comment]
Wrong project. Issues regarding https://github.com/SgtSilvio/android-retrofix should be be opened in that project: https://github.com/SgtSilvio/android-retrofix/issues
